/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as Verify_phoneRouteImport } from './routes/verify_phone'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SendMoneyRouteImport } from './routes/sendMoney'
import { Route as Reset_passwordRouteImport } from './routes/reset_password'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as NotificationRouteImport } from './routes/notification'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as FraudRouteImport } from './routes/fraud'
import { Route as Forgot_passwordRouteImport } from './routes/forgot_password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'

const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const Verify_phoneRoute = Verify_phoneRouteImport.update({
  id: '/verify_phone',
  path: '/verify_phone',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SendMoneyRoute = SendMoneyRouteImport.update({
  id: '/sendMoney',
  path: '/sendMoney',
  getParentRoute: () => rootRouteImport,
} as any)
const Reset_passwordRoute = Reset_passwordRouteImport.update({
  id: '/reset_password',
  path: '/reset_password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationRoute = NotificationRouteImport.update({
  id: '/notification',
  path: '/notification',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const FraudRoute = FraudRouteImport.update({
  id: '/fraud',
  path: '/fraud',
  getParentRoute: () => rootRouteImport,
} as any)
const Forgot_passwordRoute = Forgot_passwordRouteImport.update({
  id: '/forgot_password',
  path: '/forgot_password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/forgot_password': typeof Forgot_passwordRoute
  '/fraud': typeof FraudRoute
  '/history': typeof HistoryRoute
  '/notification': typeof NotificationRoute
  '/profile': typeof ProfileRoute
  '/reset_password': typeof Reset_passwordRoute
  '/sendMoney': typeof SendMoneyRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/verify_phone': typeof Verify_phoneRoute
  '/wallet': typeof WalletRoute
  '/admin/dashboard': typeof AdminDashboardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/forgot_password': typeof Forgot_passwordRoute
  '/fraud': typeof FraudRoute
  '/history': typeof HistoryRoute
  '/notification': typeof NotificationRoute
  '/profile': typeof ProfileRoute
  '/reset_password': typeof Reset_passwordRoute
  '/sendMoney': typeof SendMoneyRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/verify_phone': typeof Verify_phoneRoute
  '/wallet': typeof WalletRoute
  '/admin/dashboard': typeof AdminDashboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/forgot_password': typeof Forgot_passwordRoute
  '/fraud': typeof FraudRoute
  '/history': typeof HistoryRoute
  '/notification': typeof NotificationRoute
  '/profile': typeof ProfileRoute
  '/reset_password': typeof Reset_passwordRoute
  '/sendMoney': typeof SendMoneyRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/verify_phone': typeof Verify_phoneRoute
  '/wallet': typeof WalletRoute
  '/admin/dashboard': typeof AdminDashboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/dashboard'
    | '/forgot_password'
    | '/fraud'
    | '/history'
    | '/notification'
    | '/profile'
    | '/reset_password'
    | '/sendMoney'
    | '/settings'
    | '/sign-in'
    | '/sign-up'
    | '/verify_phone'
    | '/wallet'
    | '/admin/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/dashboard'
    | '/forgot_password'
    | '/fraud'
    | '/history'
    | '/notification'
    | '/profile'
    | '/reset_password'
    | '/sendMoney'
    | '/settings'
    | '/sign-in'
    | '/sign-up'
    | '/verify_phone'
    | '/wallet'
    | '/admin/dashboard'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/dashboard'
    | '/forgot_password'
    | '/fraud'
    | '/history'
    | '/notification'
    | '/profile'
    | '/reset_password'
    | '/sendMoney'
    | '/settings'
    | '/sign-in'
    | '/sign-up'
    | '/verify_phone'
    | '/wallet'
    | '/admin/dashboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  Forgot_passwordRoute: typeof Forgot_passwordRoute
  FraudRoute: typeof FraudRoute
  HistoryRoute: typeof HistoryRoute
  NotificationRoute: typeof NotificationRoute
  ProfileRoute: typeof ProfileRoute
  Reset_passwordRoute: typeof Reset_passwordRoute
  SendMoneyRoute: typeof SendMoneyRoute
  SettingsRoute: typeof SettingsRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  Verify_phoneRoute: typeof Verify_phoneRoute
  WalletRoute: typeof WalletRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify_phone': {
      id: '/verify_phone'
      path: '/verify_phone'
      fullPath: '/verify_phone'
      preLoaderRoute: typeof Verify_phoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sendMoney': {
      id: '/sendMoney'
      path: '/sendMoney'
      fullPath: '/sendMoney'
      preLoaderRoute: typeof SendMoneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset_password': {
      id: '/reset_password'
      path: '/reset_password'
      fullPath: '/reset_password'
      preLoaderRoute: typeof Reset_passwordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notification': {
      id: '/notification'
      path: '/notification'
      fullPath: '/notification'
      preLoaderRoute: typeof NotificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fraud': {
      id: '/fraud'
      path: '/fraud'
      fullPath: '/fraud'
      preLoaderRoute: typeof FraudRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot_password': {
      id: '/forgot_password'
      path: '/forgot_password'
      fullPath: '/forgot_password'
      preLoaderRoute: typeof Forgot_passwordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  Forgot_passwordRoute: Forgot_passwordRoute,
  FraudRoute: FraudRoute,
  HistoryRoute: HistoryRoute,
  NotificationRoute: NotificationRoute,
  ProfileRoute: ProfileRoute,
  Reset_passwordRoute: Reset_passwordRoute,
  SendMoneyRoute: SendMoneyRoute,
  SettingsRoute: SettingsRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  Verify_phoneRoute: Verify_phoneRoute,
  WalletRoute: WalletRoute,
  AdminDashboardRoute: AdminDashboardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
